### PR TITLE
refactor: upgrade to 4.2.0, cleanup formatting, update editorconfig to be consistent with project styling.

### PR DESCRIPTION
**Pull request by jolexxa**
- Upgrades to Godot 4.2.0 by fixing the GraphNode drivers.
- Adds additional editorconfig based on https://github.com/RehanSaeed/EditorConfig/blob/main/.editorconfig with a few changes to make it compatible with the styling implied in this project.
- Updates launch.json to use `GODOT` environment variable, consistent with GodotEnv standards.
- Adds missing public API docs and adds `<GenerateDocumentationFile>` to the `.csproj` to warn if anything is undocumented in future changes.

I would also recommend making release tags pinned to the underlying Godot API, such as `1.0.0-godot.4.2.0`, as it can break when client projects using GodotTestDriver have a substantially different API version than what GodotTestDriver has.

### CODE REVIEW

**Comment by derkork** [comment]
Hi Joanna, thanks a lot for submitting this. I'm currently not very well and can't have a look at this right now. I'll check it out once I feel a bit better. Thanks again!

**Comment by jolexxa** [comment]
@derkork No worries, hope you get to feeling better soon — missed seeing you around in Chickensoft!

**Comment by derkork** [comment]
Hi, so I had a look over your PR, thanks a lot again. I'm not really sure about how to handle the API changes though. Now I have one version of test driver which works with pre 4.2 godot and another one which works with 4.2 +.  

This opens up a little maintenance headache. I don't have the bandwidth for supporting multiple Godot APIs at the same time, so it ultimately would boil down to "test driver supports the latest version" and if you need an older version of Godot supported, you'd need to take an older version of test driver. Since this is all statically compiled I cannot even do some `has_method` magic and I also cannot do an `#ifdef` because the version of Godot I'm compiling against is fixed down in the project dependencies. 

So I'm beginning to question the wisdom of implementing this in C# in the first place. In GDScript I could do a little `has_method` jig and it would all just work fine. I wonder if it would be better to reimplement this in GDScript and then just provide a little C# wrapper API on top of it. This would also have the benefit of working for both C# _and_ GDScript at the same time. On the other hand I have about zero bandwidth to rewrite this in GDScript right now. What do you think? How do you handle this with your libraries (you seem to have a lot of them going as well).

**Comment by jolexxa** [comment]
Hadn't occurred to me to have something like this in GDScript. I definitely prefer working with nuget libraries over add-ons, despite headaches like this.

The chickensoft stuff generally supports the latest version of Godot. Godot gets updates faster than I keep up, and I keep my game projects updated while working on them. That's part of the reason I've invested time into making a Godot installation tool. Many packages use a tool in their repositories that will automatically update and release them. It's still possible to cherry-pick changes and back port fixes, but I rarely have to do it.

If you'd like me to induct GodotTestDriver into the Chickensoft ecosystem, I'm more than happy to. It's extremely important to have for any kind of serious testing with Godot.

**Comment by derkork** [comment]
Okay that sounds interesting, how would this "induction into the ecosystem" work?

**Comment by jolexxa** [comment]
I think you could transfer the repository to chickensoft-games or I could fork it. Either way, it would then get maintained and published under Chickensoft, and I would edit the package id to Chickensoft.GodotTestDriver. You can mark packages as deprecated on Github and Nuget. On nuget, you can even list what the alternative package should be.

I'm happy to take it off your hands or maintain a Chickensoft version with your blessing, I just don't want to do it if you plan to maintain this since it'd be competing unnecessarily. I would offer to add you as a maintainer to Chickensoft, but there's no budget since it costs me money per month per seat since I have to pay for CI/CD minutes.

**Comment by derkork** [comment]
Okay, then let's do this, I think given the circumstances this is the best for the project. If it's all the same to you, could you fork it and give me the URL of the new thing? I'll then archive mine and link to the new one on Chickensoft and also mark the nuget versions as deprecated.

**Comment by jolexxa** [comment]
Okay, thank you. This is on my radar -- I thought my updating the SDK would fix an issue with input simulation, but it didn't actually. Seems like Godot broke it after a specific version. I'll make a Chickensoft version when I have a chance to work on this again.

**Comment by jolexxa** [comment]
@derkork I finally had a chance to sit down and get this up on Chickensoft. I'm closing this PR in favor of https://github.com/chickensoft-games/GodotTestDriver

I've credited you from the Chickensoft version of the project and implemented this PR there. In the future, I hope to automate its releases further so that very little needs to be done for the majority of Godot releases that don't break the API.

Here it is on nuget: https://www.nuget.org/packages/Chickensoft.GodotTestDriver/

**Pull request closed without merging**
